# Generated by Django 4.2.4 on 2023-08-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('address', models.TextField()),
                ('number', models.TextField()),
                ('email', models.EmailField(max_length=30)),
            ],
        ),
    ]
